# Project information
site_name: C Numérico
site_description: "Curso de C Numérico"
site_author: Rafa Rguez. Galván
repo_url: https://github.com/rrgalvan/curso-c-numerico/

# Copyright
copyright: Licencia libre bajo los términos Creative Commons Compartir-Igual 3.0. &copy; 2021 Rafa Rguez. Galván

# Structure
nav:
  - Introducción: index.md
  - Fundamentos: fundamentos.md
  - Primeros pasos: primeros_pasos.md
  - Acerca de: about.md
