# Project information
site_name: Fundamentos
site_description: "Funamentos de Métodos Numéricos"
site_author: Rafa Rguez. Galván
repo_url: https://github.com/rrgalvan/curso-c-numerico/

# Copyright
copyright: Licencia libre bajo los términos Creative Commons Compartir-Igual 3.0. &copy; 2021 Rafa Rguez. Galván

# Structure
nav:
  - Introducción: index.md
  - Primeros pasos: primeros_pasos.md
  - Acerca de: about.md

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# # JavaScript (for MathJax LaTeX)
# extra_javascript:
#   - 'javascripts/extra.js'
#   - 'javascripts/MathJax.js'
