# Project information
site_name: Fundamentos_MN
site_description: "Funamentos de Métodos Numéricos"
site_author: Rafa Rguez. Galván
repo_url: https://github.com/rrgalvan/curso-c-numerico/

# Copyright
copyright: Licencia libre bajo los términos Creative Commons Compartir-Igual 3.0. &copy; 2021 Rafa Rguez. Galván

# Structure
nav:
  - Intro: index.md
  - Taller 1: 1_primeros_pasos.md
  - Taller 2: 2_datos_funciones.md
  - Más: about.md

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# # JavaScript (for MathJax LaTeX)
# extra_javascript:
#   - 'javascripts/extra.js'
#   - 'javascripts/MathJax.js'
